### ISSUE TITLE
NoSuchMethodError org.bouncycastle.util.Arrays.copyOfRange when upgrading from 0.2.24 to 0.2.25

### ISSUE THREAD

**Issue by baumeister** [mwiede/jsch#811]
After upgrading from 0.2.24 to 0.2.25 I get the following error:

java.lang.NoSuchMethodError: 'byte[] org.bouncycastle.util.Arrays.copyOfRange(byte[], int, int)'
        at org.bouncycastle.pqc.crypto.ntruprime.SNTRUPrimeKeyPairGenerator.generateKeyPair(Unknown Source)
        at com.jcraft.jsch.bc.SNTRUP761.init(SNTRUP761.java:49)
        at com.jcraft.jsch.DHXECKEM.init(DHXECKEM.java:84)
        at com.jcraft.jsch.KeyExchange.doInit(KeyExchange.java:77)
        at com.jcraft.jsch.Session.checkKex(Session.java:3099)
        at com.jcraft.jsch.Session.checkKexes(Session.java:3077)
        at com.jcraft.jsch.Session.send_kexinit(Session.java:757)
        at com.jcraft.jsch.Session.connect(Session.java:328)

This is reproducible and reversible by downgrading back to 0.2.24.

I have have a dependency on org.apache.tika:tika-core:3.1.0, which causes a transitive dependency to org.bouncycastle:*:1.80

I don't see bouncycastle as a dependency of jsch, so not sure what to make of this.

**Comment by baumeister** [comment]
For reference: Java 24, and Session.connect is called in the following context:


```
				JSch jsch = new JSch();
				java.util.Properties config = new java.util.Properties(); 
				config.put("StrictHostKeyChecking", "no");
				session=jsch.getSession(user, host, port);
				session.setConfig(config);
				if (privateKeyFile!=null) 
					jsch.addIdentity(privateKeyFile);
				if (pwd!=null)
					session.setUserInfo(new MyUserInfo(pwd));
				session.connect(5000);
```



where MyUserInfo is the following:


```
	private static class MyUserInfo implements UserInfo, UIKeyboardInteractive {
		final String pwd;
		MyUserInfo(String pwd) {
			this.pwd = pwd;
		}
		@Override
		public String getPassphrase() {
			return null;
		}

		@Override
		public String getPassword() {
			return pwd;
		}

		@Override
		public boolean promptPassword(String message) {
			return true;
		}

		@Override
		public boolean promptPassphrase(String message) {
			return true;
		}

		@Override
		public boolean promptYesNo(String message) {
			return true;
		}

		@Override
		public void showMessage(String message) {
		}

		@Override
		public String[] promptKeyboardInteractive(String destination, String name, String instruction, String[] prompt,
				boolean[] echo) {
			return new String[] {getPassword()};
		}
	}
```

**Comment by mwiede** [comment]
hi @baumeister 

I cannot reproduce this:

```
 mvn dependency:tree
...
[INFO] --- dependency:3.7.0:tree (default-cli) @ jsch ---
[INFO] org.example:jsch:jar:1.0-SNAPSHOT
[INFO] +- com.github.mwiede:jsch:jar:0.2.25:compile
[INFO] +- org.bouncycastle:bcprov-jdk18on:jar:1.80:compile
[INFO] \- junit:junit:jar:3.8.1:test
```

```
java -version
openjdk version "24" 2025-03-18
OpenJDK Runtime Environment (build 24+36-3646)
OpenJDK 64-Bit Server VM (build 24+36-3646, mixed mode, sharing)
```

```
INFO: Connecting to localhost port 2222
INFO: Connection established
INFO: Remote version string: SSH-2.0-OpenSSH_9.9
INFO: Local version string: SSH-2.0-JSCH_0.2.25
INFO: CheckCiphers: chacha20-poly1305@openssh.com
INFO: CheckKexes: mlkem768x25519-sha256,mlkem768nistp256-sha256,mlkem1024nistp384-sha384,sntrup761x25519-sha512,sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
INFO: CheckSignatures: ssh-ed25519,ssh-ed448
DEBUG: server_host_key proposal before known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
DEBUG: server_host_key proposal after known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
INFO: SSH_MSG_KEXINIT sent
INFO: SSH_MSG_KEXINIT received
```


To me it seems, something in your setup is wrong with class loading the BC classes.

I debugged into the classes and it comes to the ones of your stack traces.

You could try disabling this by overwriting
 `session.setConfig("CheckKexes", "mlkem768x25519-sha256,mlkem768nistp256-sha256,mlkem1024nistp384-sha384,curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512");`
but when any other BC class is touched, it might fail again.

**Comment by norrisjeremy** [comment]
Hi @baumeister,

Contrary to your assertion, `org.apache.tika:tika-core:3.1.0` does not have a transitive dependency on Bouncy Castle:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------< foo:bar >-------------------------------
[INFO] Building bar 1
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.8.1:tree (default-cli) @ bar ---
[INFO] foo:bar:jar:1
[INFO] \- org.apache.tika:tika-core:jar:3.1.0:compile
[INFO]    +- org.slf4j:slf4j-api:jar:2.0.16:compile
[INFO]    \- commons-io:commons-io:jar:2.18.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.489 s
[INFO] Finished at: 2025-04-11T06:16:51-05:00
[INFO] ------------------------------------------------------------------------
```

I would recommend investigating all the libraries on your classpath and correctly determining which of them actually is pulling in Bouncy Castle.
Additionally, you may need to also investigate all the libraries on your classpath to determine if any of them may have shaded Bouncy Castle, most likely incompletely, causing the issue you are reporting.

Thanks,
Jeremy

**Comment by baumeister** [comment]
Apologies, the transitive dependencies don't come from tika-core but from some of its parser modules:

```
+--- org.apache.tika:tika-parser-pdf-module:3.1.0
|    +--- org.apache.tika:tika-parser-xmp-commons:3.1.0
|    |    +--- org.apache.pdfbox:jempbox:1.8.17
|    |    \--- org.apache.pdfbox:xmpbox:3.0.4
|    |         \--- commons-logging:commons-logging:1.3.4 -> 1.3.5
|    +--- org.apache.pdfbox:pdfbox:3.0.4
|    |    +--- org.apache.pdfbox:pdfbox-io:3.0.4
|    |    |    \--- commons-logging:commons-logging:1.3.4 -> 1.3.5
|    |    +--- org.apache.pdfbox:fontbox:3.0.4
|    |    |    +--- org.apache.pdfbox:pdfbox-io:3.0.4 (*)
|    |    |    \--- commons-logging:commons-logging:1.3.4 -> 1.3.5
|    |    \--- commons-logging:commons-logging:1.3.4 -> 1.3.5
|    +--- org.apache.pdfbox:pdfbox-tools:3.0.4
|    |    +--- commons-io:commons-io:2.18.0
|    |    \--- info.picocli:picocli:4.7.6
|    +--- org.apache.pdfbox:jempbox:1.8.17
|    +--- org.bouncycastle:bcjmail-jdk18on:1.80
|    |    \--- org.bouncycastle:bcpkix-jdk18on:[1.80,1.81) -> 1.80
|    |         \--- org.bouncycastle:bcutil-jdk18on:[1.80,1.81) -> 1.80
|    |              \--- org.bouncycastle:bcprov-jdk18on:[1.80,1.81) -> 1.80
|    +--- org.bouncycastle:bcprov-jdk18on:1.80
|    \--- org.glassfish.jaxb:jaxb-runtime:4.0.5
|         \--- org.glassfish.jaxb:jaxb-core:4.0.5
|              +--- jakarta.xml.bind:jakarta.xml.bind-api:4.0.2 (*)
|              +--- jakarta.activation:jakarta.activation-api:2.1.3
|              +--- org.glassfish.jaxb:txw2:4.0.5
|              \--- com.sun.istack:istack-commons-runtime:4.1.2
+--- org.apache.tika:tika-parser-microsoft-module:3.1.0
|    +--- org.slf4j:slf4j-api:2.0.16 -> 2.0.17
|    +--- org.apache.tika:tika-parser-html-module:3.1.0
|    |    +--- org.jsoup:jsoup:1.18.3 -> 1.19.1
|    |    \--- commons-codec:commons-codec:1.18.0
|    +--- org.apache.tika:tika-parser-text-module:3.1.0 (*)
|    +--- org.apache.tika:tika-parser-xml-module:3.1.0
|    |    \--- commons-codec:commons-codec:1.18.0
|    +--- org.apache.tika:tika-parser-mail-commons:3.1.0
|    |    +--- org.apache.james:apache-mime4j-core:0.8.12
|    |    |    \--- commons-io:commons-io:2.17.0 -> 2.18.0
|    |    \--- org.apache.james:apache-mime4j-dom:0.8.12
|    |         +--- org.apache.james:apache-mime4j-core:0.8.12 (*)
|    |         \--- commons-io:commons-io:2.17.0 -> 2.18.0
|    +--- com.pff:java-libpst:0.9.3
|    +--- org.apache.tika:tika-parser-zip-commons:3.1.0
|    |    \--- org.apache.commons:commons-compress:1.27.1
|    |         +--- commons-codec:commons-codec:1.17.1 -> 1.18.0
|    |         +--- commons-io:commons-io:2.16.1 -> 2.18.0
|    |         \--- org.apache.commons:commons-lang3:3.16.0 -> 3.17.0
|    +--- commons-codec:commons-codec:1.18.0
|    +--- org.apache.commons:commons-lang3:3.17.0
|    +--- org.apache.poi:poi:5.4.0
|    |    +--- commons-codec:commons-codec:1.17.1 -> 1.18.0
|    |    +--- org.apache.commons:commons-collections4:4.4 -> 4.5.0-M3
|    |    +--- org.apache.commons:commons-math3:3.6.1
|    |    +--- commons-io:commons-io:2.18.0
|    |    +--- com.zaxxer:SparseBitSet:1.3
|    |    \--- org.apache.logging.log4j:log4j-api:2.24.3
|    +--- org.apache.poi:poi-scratchpad:5.4.0
|    |    +--- org.apache.poi:poi:5.4.0 (*)
|    |    +--- org.apache.logging.log4j:log4j-api:2.24.3
|    |    +--- org.apache.commons:commons-math3:3.6.1
|    |    +--- commons-codec:commons-codec:1.17.1 -> 1.18.0
|    |    \--- commons-io:commons-io:2.18.0
|    +--- org.apache.poi:poi-ooxml:5.4.0
|    |    +--- org.apache.poi:poi:5.4.0 (*)
|    |    +--- org.apache.poi:poi-ooxml-lite:5.4.0
|    |    |    \--- org.apache.xmlbeans:xmlbeans:5.3.0
|    |    |         \--- org.apache.logging.log4j:log4j-api:2.24.2 -> 2.24.3
|    |    +--- org.apache.xmlbeans:xmlbeans:5.3.0 (*)
|    |    +--- org.apache.commons:commons-compress:1.27.1 (*)
|    |    +--- commons-io:commons-io:2.18.0
|    |    +--- com.github.virtuald:curvesapi:1.08
|    |    +--- org.apache.logging.log4j:log4j-api:2.24.3
|    |    \--- org.apache.commons:commons-collections4:4.4 -> 4.5.0-M3
|    +--- commons-logging:commons-logging:1.3.4 -> 1.3.5
|    +--- com.healthmarketscience.jackcess:jackcess:4.0.8
|    |    +--- org.apache.commons:commons-lang3:3.10 -> 3.17.0
|    |    \--- commons-logging:commons-logging:1.2 -> 1.3.5
|    +--- com.healthmarketscience.jackcess:jackcess-encrypt:4.0.2
|    |    +--- com.healthmarketscience.jackcess:jackcess:4.0.0 -> 4.0.8 (*)
|    |    \--- org.bouncycastle:bcprov-jdk18on:1.72 -> 1.80
|    +--- org.bouncycastle:bcjmail-jdk18on:1.80 (*)
|    \--- org.bouncycastle:bcprov-jdk18on:1.80
```

After some further investigation, all of the following is required for me to see the problem:

1. The problem does not appear if I downgrade from 0.2.25 to 0.2.24
2. The problem does not appear if I remove the dependencies on tika
3. The problem does not appear if I switch JRE from 24.fx-zulu to 23.0.2.fx-zulu (weird one)
4. The problem does not appear if I set the "CheckKexes" config as you suggested.

However, I tried to create a simple testcase with all of the above requirements but all other dependencies except for tika/jsch removed, and was not able to do so. So this seems to be more complex. But scanning through all the jars that are part of the build, I don't see any other mentions of 'bouncycastle' as part of package names, except for the official 1.80 jars that tika pulls in. Not sure how else I would find anything that would shade bouncycastle without having it in the package path.

In any case, happy with the CheckKexes setting. Thanks!

**Comment by norrisjeremy** [comment]
Hi @baumeister,

Our new 0.2.26 release should workaround the issue you were seeing without having to downgrade the JRE or changing the `CheckKexes` by internally catching any [LinkageError](https://docs.oracle.com/javase/8/docs/api/java/lang/LinkageError.html)'s (such as the [NoSuchMethoError](https://docs.oracle.com/javase/8/docs/api/java/lang/NoSuchMethodError.html)):  can you confirm?

Thanks,
Jeremy

**Comment by baumeister** [comment]
- removed the CheckKexes setting and confirmed the problem still reproduces
- changed dependency to 0.2.26 and confirmed problem is resolved

Thanks,
Timm
